// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BundleStatusResponse = { version: string, offlinePackages: number, cacheBytes: number, };

export type CancelCompileRequest = { compileId: string, };

export type CloseProjectRequest = { projectId: string, };

/**
 * `Tectonic` is the default, embedded engine; `System` shells out to a detected TeX Live/MiKTeX install.
 */
export type CompileEngine = "tectonic" | "system";

export type CompilePhase = "typeset" | "bib" | "rerun";

export type CompileReason = "edit" | "manual" | "open" | "save";

export type CompileRequest = { projectId: string, dirtyBuffers: Array<DirtyBuffer>, reason: CompileReason, engine: CompileEngine, 
/**
 * Client-chosen root override ("targeting"). `quire-core` holds no state, so this travels
 * with every call like `engine` does; `None`/absent falls through to normal detection.
 */
targetRoot?: string | null, };

export type CompileResponse = { compileId: string, status: CompileStatus, 
/**
 * In the shadow dir; `null` if the compile produced no PDF.
 */
pdfPath: string | null, changedPages: Array<number>, pageCount: number, durationMs: number, diagnostics: Array<Diagnostic>, 
/**
 * Bare package/class names (no extension), populated only when `status` is `"packages-missing"`.
 */
missingPackages: Array<string>, 
/**
 * The active Tectonic bundle's digest, hex-formatted. Real today; the curated versioned bundle *strategy* doesn't exist yet.
 */
bundleVersion: string, 
/**
 * Whichever file this compile actually used as root - the request's `targetRoot` when it
 * resolved, otherwise whatever automatic detection picked. Always populated; root resolution
 * happens before any response (including `EngineMissing`) is constructed.
 */
root: string, };

export type CompileStatus = "ok" | "errors" | "cancelled" | "engine-missing" | "packages-missing";

export type CompletionItem = { label: string, kind: CompletionKind, 
/**
 * May contain `${1:tabstops}`.
 */
insert: string, detail?: string | null, documentation?: string | null, 
/**
 * TeX source for KaTeX rendering, e.g. `"\\alpha"`.
 */
symbolPreview?: string | null, 
/**
 * Lower first.
 */
sortPriority: number, };

export type CompletionKind = "command" | "environment" | "label" | "citation" | "path" | "package" | "macro" | "symbol";

export type CompletionRequest = { projectId: string, uri: string, position: Position, text: string, };

export type CopyEntryRequest = { projectId: string, uri: string, destParentUri: string, newName?: string | null, };

/**
 * Emitted via `onEvent`. `IndexUpdated`/`BundleFetch` are never emitted yet.
 */
export type CoreEvent = { "kind": "compile-started", compileId: string, } | { "kind": "compile-progress", compileId: string, phase: CompilePhase, pass: number, } | { "kind": "compile-finished", result: CompileResponse, } | { "kind": "files-changed", projectId: string, uris: Array<string>, } | { "kind": "index-updated", projectId: string, } | { "kind": "bundle-fetch", package: string, bytes: number, done: boolean, };

export type CreateDirectoryRequest = { projectId: string, parentUri: string, name: string, };

export type CreateFileRequest = { projectId: string, parentUri: string, name: string, };

/**
 * `engine`/`version` are `None` together iff `available` is `false`.
 */
export type DetectSystemTexResponse = { available: boolean, engine: SystemTexEngine | null, version: string | null, };

export type Diagnostic = { 
/**
 * `null` when the log gives no location.
 */
uri: string | null, range: DiagnosticRange | null, severity: Severity, 
/**
 * PLAIN ENGLISH. Never the raw TeX string.
 */
message: string, rawMessage: string, hint?: string | null, 
/**
 * Stable id, e.g. `"missing-dollar"`.
 */
code?: string | null, };

export type DiagnosticRange = { start: Position, end: Position, };

export type DirtyBuffer = { uri: string, text: string, };

/**
 * Returned by create/rename/move/copy: the entry's resulting absolute path.
 */
export type EntryResponse = { uri: string, };

export type ExplorerNode = { uri: string, name: string, kind: ExplorerNodeKind, 
/**
 * `Some` (possibly empty) for a directory, `None` for a file.
 */
children: Array<ExplorerNode> | null, };

export type ExplorerNodeKind = "file" | "directory";

/**
 * `name` is the package/class name, not a filename. `bytes` is the real downloaded size, known only after the fact.
 */
export type FetchedPackage = { name: string, bytes: bigint, };

/**
 * Flat list from [`crate::project::FileGraph`] (the LaTeX dependency graph), not a directory walk.
 */
export type FileNode = { uri: string, name: string, kind: FileNodeKind, };

export type FileNodeKind = "tex" | "graphic" | "bib" | "class" | "package";

export type InstallPackageRequest = { name: string, };

/**
 * `bytes` is `None` for `Core` entries - a fixed app asset, not a meaningful per-package number.
 */
export type InstalledPackage = { name: string, bytes: bigint | null, source: PackageSource, };

export type ListProjectTreeRequest = { projectId: string, };

export type MoveEntryRequest = { projectId: string, uri: string, newParentUri: string, };

export type OpenProjectRequest = { path: string, };

export type OpenProjectResponse = { projectId: string, root: string, rootConfidence: RootConfidence, 
/**
 * Populated when `rootConfidence` is `"ambiguous"`.
 */
candidates: Array<string>, files: Array<FileNode>, engineAvailable: boolean, 
/**
 * Plain-English; `null` when versions match or nothing was pinned yet. Never blocks `openProject`.
 */
bundleVersionNotice: string | null, };

export type OutlineNode = { label: string, kind: OutlineNodeKind, position: Position, children: Array<OutlineNode>, };

/**
 * `outline` never returns more than an empty list today.
 */
export type OutlineNodeKind = "part" | "chapter" | "section" | "subsection" | "subsubsection" | "label";

export type OutlineRequest = { projectId: string, uri: string, };

/**
 * `Core` ships in the app and is never removable; `Cache` was fetched on demand and is removable.
 */
export type PackageSource = "core" | "cache";

export type Position = { 
/**
 * 0-based.
 */
line: number, 
/**
 * 0-based, UTF-16 code units (matches CodeMirror/LSP convention).
 */
column: number, };

export type PrefetchPackagesRequest = { projectId: string, };

export type PrefetchPackagesResponse = { fetched: Array<FetchedPackage>, failed: Array<string>, };

export type ReadFileRequest = { uri: string, };

export type RemovePackageRequest = { name: string, };

export type RenameEntryRequest = { projectId: string, uri: string, newName: string, };

export type ReplaceInProjectRequest = { projectId: string, query: string, replacement: string, caseSensitive: boolean, wholeWord: boolean, regex: boolean, dirtyBuffers: Array<DirtyBuffer>, };

export type ReplaceInProjectResponse = { files: Array<ReplacedFile>, };

export type ReplacedFile = { uri: string, replacements: number, 
/**
 * Full new file content, so the client can refresh an open tab's buffer without a second readFile round trip.
 */
newText: string, };

export type RootConfidence = "explicit" | "inferred" | "ambiguous";

export type SearchMatch = { uri: string, line: number, column: number, lineText: string, matchLength: number, };

export type SearchProjectRequest = { projectId: string, query: string, caseSensitive: boolean, wholeWord: boolean, regex: boolean, dirtyBuffers: Array<DirtyBuffer>, };

export type SearchProjectResponse = { matches: Array<SearchMatch>, 
/**
 * True when the match count hit the internal cap - the list isn't exhaustive.
 */
truncated: boolean, };

export type SetRootRequest = { projectId: string, uri: string, };

export type Severity = "error" | "warning" | "info";

/**
 * `xelatex` is preferred (checked first) since Tectonic's own embedded engine is XeTeX-based too.
 */
export type SystemTexEngine = "xelatex" | "pdflatex";

export type WriteFileRequest = { uri: string, text: string, };
