// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BundleStatusResponse = { version: string, offlinePackages: number, cacheBytes: number, };

export type CancelCompileRequest = { compileId: string, };

export type CloseProjectRequest = { projectId: string, };

export type CompilePhase = "typeset" | "bib" | "rerun";

export type CompileReason = "edit" | "manual" | "open" | "save";

export type CompileRequest = { projectId: string, dirtyBuffers: Array<DirtyBuffer>, reason: CompileReason, };

export type CompileResponse = { compileId: string, status: CompileStatus, 
/**
 * In the shadow dir; `null` if the compile produced no PDF.
 */
pdfPath: string | null, changedPages: Array<number>, pageCount: number, durationMs: number, 
/**
 * Always empty today -- log translation isn't implemented yet.
 */
diagnostics: Array<Diagnostic>, 
/**
 * Populated only when `status` is `"packages-missing"`, so always empty today.
 */
missingPackages: Array<string>, 
/**
 * The active Tectonic bundle's digest, hex-formatted. Real today; the curated versioned bundle *strategy* doesn't exist yet.
 */
bundleVersion: string, };

export type CompileStatus = "ok" | "errors" | "cancelled" | "engine-missing" | "packages-missing";

export type CompletionItem = { label: string, kind: CompletionKind, 
/**
 * May contain `${1:tabstops}`.
 */
insert: string, detail?: string | null, documentation?: string | null, 
/**
 * TeX source for KaTeX rendering, e.g. `"\\alpha"`.
 */
symbolPreview?: string | null, 
/**
 * Lower first.
 */
sortPriority: number, };

export type CompletionKind = "command" | "environment" | "label" | "citation" | "path" | "package" | "macro" | "symbol";

export type CompletionRequest = { projectId: string, uri: string, position: Position, text: string, };

/**
 * Emitted via `onEvent`. `IndexUpdated`/`BundleFetch` are never emitted yet.
 */
export type CoreEvent = { "kind": "compile-started", compileId: string, } | { "kind": "compile-progress", compileId: string, phase: CompilePhase, pass: number, } | { "kind": "compile-finished", result: CompileResponse, } | { "kind": "files-changed", projectId: string, uris: Array<string>, } | { "kind": "index-updated", projectId: string, } | { "kind": "bundle-fetch", package: string, bytes: number, done: boolean, };

export type Diagnostic = { 
/**
 * `null` when the log gives no location.
 */
uri: string | null, range: DiagnosticRange | null, severity: Severity, 
/**
 * PLAIN ENGLISH. Never the raw TeX string.
 */
message: string, rawMessage: string, hint?: string | null, 
/**
 * Stable id, e.g. `"missing-dollar"`.
 */
code?: string | null, };

export type DiagnosticRange = { start: Position, end: Position, };

export type DirtyBuffer = { uri: string, text: string, };

/**
 * Flat list from [`crate::project::FileGraph`] (the LaTeX dependency graph), not a directory walk.
 */
export type FileNode = { uri: string, name: string, kind: FileNodeKind, };

export type FileNodeKind = "tex" | "graphic";

export type OpenProjectRequest = { path: string, };

export type OpenProjectResponse = { projectId: string, root: string, rootConfidence: RootConfidence, 
/**
 * Populated when `rootConfidence` is `"ambiguous"`.
 */
candidates: Array<string>, files: Array<FileNode>, engineAvailable: boolean, };

export type OutlineNode = { label: string, kind: OutlineNodeKind, position: Position, children: Array<OutlineNode>, };

/**
 * `outline` never returns more than an empty list today.
 */
export type OutlineNodeKind = "part" | "chapter" | "section" | "subsection" | "subsubsection" | "label";

export type OutlineRequest = { projectId: string, uri: string, };

export type Position = { 
/**
 * 0-based.
 */
line: number, 
/**
 * 0-based, UTF-16 code units (matches CodeMirror/LSP convention).
 */
column: number, };

/**
 * Not implemented yet.
 */
export type PrefetchPackagesRequest = { projectId: string, };

export type PrefetchPackagesResponse = { fetched: Array<string>, failed: Array<string>, };

export type ReadFileRequest = { uri: string, };

export type RootConfidence = "explicit" | "inferred" | "ambiguous";

export type SetRootRequest = { projectId: string, uri: string, };

export type Severity = "error" | "warning" | "info";

export type WriteFileRequest = { uri: string, text: string, };
