// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BundleStatusResponse = { version: string, offlinePackages: number, cacheBytes: number, };

export type CancelCompileRequest = { compileId: string, };

export type CloseProjectRequest = { projectId: string, };

export type CompilePhase = "typeset" | "bib" | "rerun";

export type CompileReason = "edit" | "manual" | "open" | "save";

export type CompileRequest = { projectId: string, dirtyBuffers: Array<DirtyBuffer>, reason: CompileReason, };

export type CompileResponse = { compileId: string, status: CompileStatus, 
/**
 * In the shadow dir. `null` when the compile produced no PDF (an
 * error before typesetting started, for example).
 */
pdfPath: string | null, 
/**
 * For incremental re-render (task 1.7).
 */
changedPages: Array<number>, pageCount: number, durationMs: number, 
/**
 * Always empty today -- log parsing / plain-English translation is
 * M3.10 (Section 9.5). A compile error's message still reaches the
 * caller, just via the JSON-RPC error object, not this list.
 */
diagnostics: Array<Diagnostic>, 
/**
 * Populated when `status` is `"packages-missing"` -- so always empty
 * today, since that status is never produced (see [`CompileStatus`]).
 */
missingPackages: Array<string>, 
/**
 * The active Tectonic bundle's digest, formatted as hex. Real and
 * meaningful today (every compile already resolves a bundle via
 * `PersistentConfig::default_bundle`) even though the curated,
 * versioned bundle *strategy* from Section 9.6 (M4) doesn't exist
 * yet -- this is "which set of packages was actually used," not
 * "which named release of quire's own bundle."
 */
bundleVersion: string, };

export type CompileStatus = "ok" | "errors" | "cancelled" | "engine-missing" | "packages-missing";

export type CompletionItem = { label: string, kind: CompletionKind, 
/**
 * May contain `${1:tabstops}`.
 */
insert: string, 
/**
 * e.g. bib entry title, package name.
 */
detail?: string | null, documentation?: string | null, 
/**
 * TeX source for KaTeX rendering, e.g. `"\\alpha"`.
 */
symbolPreview?: string | null, 
/**
 * Lower first.
 */
sortPriority: number, };

export type CompletionKind = "command" | "environment" | "label" | "citation" | "path" | "package" | "macro" | "symbol";

export type CompletionRequest = { projectId: string, uri: string, position: Position, text: string, };

/**
 * Emitted, not returned -- subscribed to via `onEvent`. `IndexUpdated`
 * and `BundleFetch` are never emitted today: no completion index (M3) or
 * bundle/package-fetch system (M4) exists yet to emit them. Kept in the
 * frozen shape for the same reason as [`CompileStatus`]'s unreachable
 * variants.
 */
export type CoreEvent = { "kind": "compile-started", compileId: string, } | { "kind": "compile-progress", compileId: string, phase: CompilePhase, pass: number, } | { "kind": "compile-finished", result: CompileResponse, } | { "kind": "files-changed", projectId: string, uris: Array<string>, } | { "kind": "index-updated", projectId: string, } | { "kind": "bundle-fetch", package: string, bytes: number, done: boolean, };

export type Diagnostic = { 
/**
 * `null` when the log gives no location.
 */
uri: string | null, range: DiagnosticRange | null, severity: Severity, 
/**
 * PLAIN ENGLISH. Never the raw TeX string.
 */
message: string, 
/**
 * Original, for the detail view.
 */
rawMessage: string, 
/**
 * Suggested fix.
 */
hint?: string | null, 
/**
 * Stable id, e.g. `"missing-dollar"`.
 */
code?: string | null, };

export type DiagnosticRange = { start: Position, end: Position, };

export type DirtyBuffer = { uri: string, 
/**
 * Unsaved editor state.
 */
text: string, };

/**
 * See the module docs: derived from [`crate::project::FileGraph`] (the
 * LaTeX dependency graph), not a general directory walk.
 */
export type FileNode = { uri: string, name: string, kind: FileNodeKind, };

export type FileNodeKind = "tex" | "graphic";

export type OpenProjectRequest = { path: string, };

export type OpenProjectResponse = { projectId: string, 
/**
 * Detected root document.
 */
root: string, rootConfidence: RootConfidence, 
/**
 * Populated when `rootConfidence` is `"ambiguous"`.
 */
candidates: Array<string>, files: Array<FileNode>, engineAvailable: boolean, };

export type OutlineNode = { label: string, kind: OutlineNodeKind, position: Position, children: Array<OutlineNode>, };

/**
 * M3 scaffolding -- see the module docs. `outline` never returns anything
 * but an empty list today; this shape is what a real implementation would
 * need to fill in.
 */
export type OutlineNodeKind = "part" | "chapter" | "section" | "subsection" | "subsubsection" | "label";

export type OutlineRequest = { projectId: string, uri: string, };

export type Position = { 
/**
 * 0-based.
 */
line: number, 
/**
 * 0-based, UTF-16 code units (matches CodeMirror/LSP convention).
 */
column: number, };

/**
 * M4 scaffolding -- see the module docs.
 */
export type PrefetchPackagesRequest = { projectId: string, };

export type PrefetchPackagesResponse = { fetched: Array<string>, failed: Array<string>, };

export type ReadFileRequest = { uri: string, };

export type RootConfidence = "explicit" | "inferred" | "ambiguous";

export type SetRootRequest = { projectId: string, uri: string, };

export type Severity = "error" | "warning" | "info";

export type WriteFileRequest = { uri: string, text: string, };
