// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {verbatimTokenizer} from "./tokens"
const spec_Command = {__proto__:null,"\\text":68, "\\mbox":68, "\\textrm":68, "\\textbf":68, "\\textit":68, "\\textsf":68, "\\texttt":68, "\\emph":68, "\\textnormal":68, "\\intertext":68, "\\caption":68, "\\begin":70, "\\end":72, "\\[":84, "\\]":86, "\\(":88, "\\)":90}
const spec_EnvName = {__proto__:null,equation:74, "equation*":74, align:74, "align*":74, gather:74, "gather*":74, multline:74, "multline*":74, eqnarray:74, "eqnarray*":74, math:74, displaymath:74, flalign:74, "flalign*":74, verbatim:78, "verbatim*":78, lstlisting:78, minted:78}
export const parser = LRParser.deserialize({
  version: 14,
  states: "+|QYQPOOOOQO'#Ca'#CaOOQO'#Cf'#CfOwQPO'#CeO|QPO'#CoO!TQPO'#CpO!fQPO'#CqOOQO'#Cs'#CsO!wQPO'#CrOOQO'#Cv'#CvO#YQPO'#CuOOQO'#C}'#C}O#kQPO'#C}OOQO'#Cx'#CxQYQPOOO#pQQO,59POOQO,59Z,59ZO#{QPO,59ZO$SQPO'#CkOOQO'#DS'#DSO#kQPO'#DSOOQO'#Cy'#CyO$eQPO,59[OOQO,59[,59[O$vQPO,59]OOQO,59],59]O!wQPO,59^OOQO'#Ct'#CtOOQO,59^,59^O#YQPO,59aOOQO'#Cw'#CwOOQO,59a,59aO%XQPO'#CbOOQO,59i,59iOOQO-E6v-E6vO%`QPO1G.kOOQO'#Cj'#CjO%eQPO1G.oOOQO'#Cn'#CnO%jQPO1G.sOOQO1G.u1G.uOOQO,59V,59VO%oQPO,59VOOQO,59n,59nOOQO-E6w-E6wOOQO1G.v1G.vOOQO1G.w1G.wOOQO1G.x1G.xOOQO1G.{1G.{OOQO,58|,58|O&QQPO,58|O&XQPO7+$VO&`QPO7+$ZO&qQTO7+$_OOQO1G.q1G.qOOQO1G.h1G.hOOQO'#Ch'#ChO&yQPO<<GqO&XQPO<<GqO&`QPO<<GuO'OQPO<<GuO'TQPO<<GyO&lQPO<<GyO'YQQOAN=]O'_QPOAN=]O'dQPOAN=aO'iQQOAN=aO#vQQOAN=eO'nQPOAN=eO'sQPOG22wO'xQQOG22wO'iQQOG22{O'}QPOG22{O(SQPOG23PO#vQQOG23POOQOLD(cLD(cO(XQPOLD(cO(^QPOLD(gOOQOLD(gLD(gOOQOLD(kLD(kO(cQPOLD(kOOQO!$'K}!$'K}OOQO!$'LR!$'LROOQO!$'LV!$'LV",
  stateData: "(k~OpOSQOS~OSZOVSO`ZOrPOsQOxTOyUOzVO|XO~OV_O~OW`O~PYOScOVbO`cOrPOxgO~OScOVbO`cOrPOyiO~OScOVbO`cOrPO{kO~OScOVbO`cOrPO}nO~OVpO~OZsOutOwvO~OWxO~PYOScOVbOWyO`cOrPO~OScOVbO`cOrPOx}O~OScOVbO`cOrPOy!OO~OW!RO~PYOW!TO~OW!UO~OW!VO~OScOVbOW!WO`cOrPO~OW!XO~PYOt!YO~PYOScOVbO`cOrPOt!YO~OP!`Ot!YO~OV!aO~OV!dO~OV!eO~OZ!gO~OV!hO~OV!iO~OutO~OV!lO~OW!mO~OZ!nO~OW!pO~OW!qO~OW!sO~OW!tO~OW!uO~O`p~",
  goto: "&YwPPPPPx!bPP!h!rP!|!h#`#iP!h#w!h!h!h!h$Q$[!h$b$l$r%UPPP%pPPPP%z`[OS^ap!S!T![idTUWYbfhjmz!U!]Qq[R{daZOS^ap!S!T![aROS^ap!S!T![Q!Z!TQ!^!UQ!_!VQ!b![Q!c!]R!f!`Qu_Q!j!dR!o!iicTUWYbfhjmz!U!]Qw_Q!k!eR!r!laWOS^ap!S!T![QlWR!PjaYOS^ap!S!T![QoYR!QmQ^OQaSWr^a!S![Q!SpR![!TQfTQhUQjWQmYQzb[|fhjmz!]R!]!Ua]OS^ap!S!T![ieTUWYbfhjmz!U!]",
  nodeNames: "⚠ VerbatimBody Comment Document Command TextCommand TextArg { } Environment BeginKw EnvName EndKw MathEnvironment MathEnvName MathGroup Text VerbatimEnvironment VerbatimEnvName Group InlineMath DisplayMathDollar DisplayMathBracket MathBracketOpen MathBracketClose InlineMathParen MathParenOpen MathParenClose",
  maxTerm: 45,
  skippedNodes: [0,2],
  repeatNodeCount: 2,
  tokenData: "+T~RuOX#fXZ$aZ]%U]^$a^p#fpq$aqt#ftu'Wuv'ev!c#f!c!}'|!}#O#f#O#P)y#P#T#f#T#o'|#o#p*y#p#q#f#q#r+O#r#y#f#y#z%U#z$f#f$f$g%U$g#BY#f#BY#BZ%U#BZ$IS#f$IS$I_%U$I_$I|#f$I|$JO%U$JO$JT#f$JT$JU%U$JU$KV#f$KV$KW%U$KW&FU#f&FU&FV%U&FV;'S#f;'S;=`$Z<%lO#fP#kY`POX#fZ]#f^p#fqt#fv#O#f#P#o#f#p#q#f#r;'S#f;'S;=`$Z<%lO#fP$^P;=`<%l#f~$fYp~X^$apq$a#y#z$a$f$g$a#BY#BZ$a$IS$I_$a$I|$JO$a$JT$JU$a$KV$KW$a&FU&FV$a~%]m`Pp~OX#fXZ$aZ]%U]^$a^p#fpq$aqt#fv#O#f#P#o#f#p#q#f#r#y#f#y#z%U#z$f#f$f$g%U$g#BY#f#BY#BZ%U#BZ$IS#f$IS$I_%U$I_$I|#f$I|$JO%U$JO$JT#f$JT$JU%U$JU$KV#f$KV$KW%U$KW&FU#f&FU&FV%U&FV;'S#f;'S;=`$Z<%lO#f~']Px~tu'`~'eOy~~'jSQ~OY'eZ;'S'e;'S;=`'v<%lO'e~'yP;=`<%l'eR(T_ZQ`POX#fZ]#f^p#fqt#fvz#fz{)S{!c#f!c!}'|!}#O#f#P#T#f#T#o'|#p#q#f#r;'S#f;'S;=`$Z<%lO#fR)ZYZQ`POX#fZ]#f^p#fqt#fv#O#f#P#o#f#p#q#f#r;'S#f;'S;=`$Z<%lO#f~)|VO!c*c!c!}*h!}#T*c#T#o*h#o;'S*c;'S;=`*s<%lO*c~*hOS~~*mQS~!c!}*h#T#o*h~*vP;=`<%l*c~+OOV~~+TOW~",
  tokenizers: [0, 1, verbatimTokenizer],
  topRules: {"Document":[0,3]},
  specialized: [{term: 4, get: (value: keyof typeof spec_Command) => spec_Command[value] || -1},{term: 11, get: (value: keyof typeof spec_EnvName) => spec_EnvName[value] || -1}],
  tokenPrec: 346
})
